### ISSUE TITLE
Decide on what gets put where, and how

### ISSUE THREAD

**Issue by MattBlissett** [gbif/doc-documentation-guidelines#14]
The [Asciidoc experiment](https://github.com/gbif/effective-nodes-guidance/issues/12) is a two-line Jenkins build, so there's probably not much overhead for Informatics. This helps us compare other free/commercial services. I had thought they were offering a lot more, but there are probably still some features that wouldn't be worth our time to implement, like print colour profiles.

Decisions:
- [x] Target format(s) : HTML, single page HTML, PDF, ePUB etc
- [x] Free, paid-for or GBIF-run build (i.e. GBIF Jenkins, Gitbook, electric books etc)
- [x] Final destination of HTML/PDF (e.g. building with GH Pages forces hosting by Github, some services include hosting, affected by...)
- [ ] How much to integrate with the portal

I suggest:
- [x] Adding an Asciidoc stylesheet for both PDF and HTML (or for hosted services, seeing how to restyle things).
- [x] Testing multi-page HTML, if that might be needed
- [x] Testing a translation
- [x] Testing adding images like screenshots

**Comment by kcopas** [comment]
Closing in favour of open issue #13 on the last unresolved item here: 'how much to integrate with the portal'.

Current thought is that this will be done through card-based 'features' on a planned landing page template for the site's documents. Curated access to individual docs (and even potentially sets of docs).
