### ISSUE TITLE
Broke link in a document on review

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/doc-documentation-guidelines#17]
Hi!, 
I can't find the version for review in the GBIF document page for the Georeferencing Calculator Manual. Hope you can help me.

Thanks in advance!

**Comment by RicardoOrtizG** [comment]
Already found it.
https://docs.gbif-uat.org/georeferencing-calculator-manual/1.0/en/

**Comment by kcopas** [comment]
That document is not yet out for review @RicardoOrtizG 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
