### ISSUE TITLE
Documentation licences and authorship

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-documentation-guidelines#3]
A resolution/document is needed from the EP (in principle) on how to deal with licences and authorship for the documentation. I put this two together as they might overlap in some points...

Some of the topics that would need to be addressed are:
- Which are the possible options for licences (probably accompanied by some sort of explanation).
- How to deal with documents that had previous versions already licensed.
- Licences/rights for media included in the documentation.
- Who is responsible for communicating with the rights holder to sort out how to deal with new versions of documentation (eg, cases where universities were cited as rights holder of previous versions of a document but where no actual license is declared in the document). Would the Editorial Panel deal with this? Would some legal representative from eg GBIF deal with it?
- How to deal with documents that had previous versions with (totally or partially) different authors.
- What to consider author, what contributor, what to just acknowledge (as for the [documentation template](https://github.com/gbif/doc-template/blob/master/contributors.adoc), authors would be called contributors).

**Comment by kcopas** [comment]
> Which are the possible options for licences (probably accompanied by some sort of explanation).

As [mentioned](https://github.com/gbif/doc-documentation-guidelines/issues/2) just a moment ago, a recommendation will be coming to the panel for its prompt consideration. CC BY 4.0 will be the proposal.

> How to deal with documents that had previous versions already licensed.

This chain of provenance (if you will) should be recorded in the Document control section of the colophon e.g. https://labs.gbif.org/documents/effective-nodes-guidance/en/#_document_control. Note that this is in keeping with the Creative Commons legal code, which notes that 'If [a licensed] work is shared in an adapted version, it must be indicated that it is a modified version.'

> Licences/rights for media included in the documentation.

Yes, as and where needed, definitely. 

> Who is responsible for communicating with the rights holder to sort out how to deal with new versions of documentation (eg, cases where universities were cited as rights holder of previous versions of a document but where no actual license is declared in the document). Would the Editorial Panel deal with this? Would some legal representative from eg GBIF deal with it?

I would propose that the Secretariat should facilitate this, based on requests for guidance and direction from commissioned authors.

> How to deal with documents that had previous versions with (totally or partially) different authors.

See above.

> What to consider author, what contributor, what to just acknowledge (as for the documentation template, authors would be called contributors).

Thanks for noticing this fine distinction! 

For the past 4-5 years, GBIF has had a policy of publishing documents with institutional authorship, e.g. GBIF Secretariat. By way of giving some individual credit on these works, however, we cite those who would more generally be considered authors and coauthors as 'Contributors'. Thus, you see @melianieraymond et al. listed as [contributors](https://labs.gbif.org/documents/effective-nodes-guidance/en/#_contributors) to the nodes guidance doc. 

I see no good reason not to call authors 'Authors' in commissioned documentation. I'll add the Autores section to the OpenRefine colophon now…

**Comment by kcopas** [comment]
![Screenshot 2019-04-23 at 14 45 24](https://user-images.githubusercontent.com/12379236/56581990-7b723600-65d6-11e9-8b5d-2be06fda7e2f.png)

**Comment by kcopas** [comment]
Works as directed in the rendered document, even if it looks a little dicey in the raw form.
