### ISSUE TITLE
Updating documentation: original document 

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-documentation-guidelines#4]
When updating a given document, should it be a pre-requisite that the original document (or the immediate previous version if there are more than one) be available in the same repository for reference?

**Comment by kcopas** [comment]
I don't believe so. See item #2 [here](https://github.com/gbif/doc-documentation-guidelines/issues/3#issuecomment-485780165).

Maintain the chain of provenance in Document control and link to the original source using a persistent identifier.

In the case of digital documentation going forward, users will be able to roll back to previous releases (provided that we mark them as such).
