### ISSUE TITLE
DOIs for documentation images

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-documentation-guidelines#5]
We have found some publications that have images with DOIs assigned to them. For an example see:
https://riojournal.com/article/32449/element/2/3571126/, where e.g., 10.3897/rio.4.e32449.figure1 is the doi for Figure 1, 10.3897/rio.4.e32449.figure4 is the doi for Figure 4, etc.

Would this be something to consider for the documentation?

**Comment by kcopas** [comment]
This idea is worth considering for new works, but not for, say, screenshots.

Seems like something authors should discuss with Secretariat staff where appropriate—or have Secretariat staff flag as an option upon review of text. In the event that DOIs are assigned, this should be done through GBIF's DataCite account.

**Comment by dnoesgaard** [comment]
In my opinion it would really only make sense if said images were hosted independently, not just part of a publication. Otherwise it would be like assigning individual DOIs to paragraphs of a text and having the DOIs point to anchors within the same text.
