### ISSUE TITLE
Hyperlinks/anchors within a document

### ISSUE THREAD

**Issue by pzermoglio** [gbif/doc-documentation-guidelines#6]
In some documents, particularly in their digital form, it is important to include quick references to other sections of the same or other documents. This is easily done in the commonly used text editors (e.g., word, google docs, etc.) but if done in the regular way, it does not transfer well when passing to adocs. What would be the recommendation for authors about this? How should they denote links and anchors?

**Comment by kcopas** [comment]
If anything, this capability seems overdeveloped in AsciiDoc: 
https://asciidoctor.org/docs/user-manual/#xref

Our documentation should adapt and simplify this guidance to the most frequent and relevant uses.

**Comment by kcopas** [comment]
Asciidoc provides automated TOCs and links to all sections preceded by a header style. All good here.
