### ISSUE TITLE
Add Google Analytics to documentation

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-documentation-guidelines#7]
@MattBlissett mentioned a plug-in to investigate…

**Comment by kcopas** [comment]
Lo! and behold!

**GoogleAnalyticsDocinfoProcessor**, lib/google-analytics-docinfoprocessor.rb
Adds the Google Analytics code for the account identified by the google-analytics-account attribute to the bottom of the HTML document.
https://github.com/asciidoctor/asciidoctor-extensions-lab

Shall I generate GA codes for our current set of docs?

**Comment by MattBlissett** [comment]
I think this relies on the domain, so it should be made for docs.gbif.org.

**Comment by MattBlissett** [comment]
This was done some time ago.
