### ISSUE TITLE
Explore use of allcontributors bot

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-documentation-guidelines#8]
[Allcontributors bot](https://allcontributors.org) might be helpful in automating the recording of contributions by volunteers, especially translators. 

Yr opinion welcomed @MattBlissett…

**Comment by MattBlissett** [comment]
Potentially, but I think you need to decide whether it's more work to use the bot or just to do it yourself.  That depends how many contributors you expect.

Either way, you need a file like `CONTRIBUTORS.adoc/csv` which could either be Asciidoctor code, or something structured that could be converted.
```
Matthew Blissett,GBIF Secretariat,https://orcid.org/0000-0003-0623-6682
```

For people who only contribute to the translation, they could use `translations/es.add` to be credited only in that translation.
