### ISSUE TITLE
Add 'Edit on GitHub' button to HTML version

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-documentation-guidelines#9]
The one addition I'd request is a way of linking back from an HTML version to its GitHub repo.

I can create an image, but I think this should be an inviting interactive element, very button-like.

Precedent I have in mind is GitBook's use of something like this:
![Screenshot 2019-04-23 at 16 49 13](https://user-images.githubusercontent.com/12379236/56590823-fe4fbc80-65e7-11e9-8d66-6895db20832f.png)

**Comment by MattBlissett** [comment]
Done, see https://docs.gbif-uat.org/openrefine-guide/1.0/ for example.

Styling is not my strong suit, and can be reviewed with the rest of the overall style (currently 100% the default).

**Comment by kcopas** [comment]
Actually, that's very nice. 

I might opt for 'View source on GitHub' but can easily wrangle—thanks.

**Comment by MattBlissett** [comment]
You can edit the translations (indeed, someone must add French and Portuguese) in https://github.com/gbif/gbif-asciidoctor-toolkit/tree/master/gbif-extensions/lib/translate-labels

Or, the same attributes can be set in a document to override these defaults.
